# %n = player name
# %i = item id
# %x = X location
# %y = Y location
# %z = Z location
# %w = world

Notify:
    Player: true
    PlayerMessage: "This item (%i) is not allowed."
    Admins: true
    AdminMessage: "Player %n tried to get item %i @ %x, %y, %z in the world %w."

DisallowedItems:
    - '5'
    - '5:1'
    - '5:2'

#Potions do not actually work yet. Sorry :)
DisallowedPotions:
    - 'weakness long'

StopCrafting: true
StopItemPickup: true
#This means that the player CAN NOT craft/pickup the item
#if they HAVE the permission node:
# noitem.nocraft.<item#>[.datavalue] or
# noitem.nopickup.<item#>[.datavalue]
#This option overrides the DisallowedItems list.
# noitem.allitems overrides ALL (DisallowedItems and PerItemPermissions)

PerItemPermissions: true

Debugging: false