name: NoItem
version: 1.4
description: Stops certain items from being crafted/picked up, effectivally removing them on the server.
author: nala3

main: net.worldoftomorrow.nala.ni.NoItem
database: false