name: NoItem
version: ${project.version}-${BUILD_NUMBER}
website: http://dev.bukkit.org/server-mods/noitem/
description: An advanced item control plugin which also supports custom blocks.
authors: [nala3]

main: net.worldoftomorrow.nala.ni.NoItem
database: false
softdepend: [Vault]

permissions:
  noitem.admin:
    default: op
    description: Allows access to noitem commands and admin notifications
  noitem.allitems:
    default: op
    description: Negates all rescrictions on the player
  noitem.nocraft.*:
    description: Blocks user from crafting all items
  noitem.nopickup.*:
    description: Blocks user from picking up all items
  noitem.nodrop.*:
    description: Blocks user from dropping all items
  noitem.nobrew.*:
    description: Blocks a user from brewing all potions
  noitem.nouse.*:
    description: Blocks a user from using all items
  noitem.nohold.*:
    description: Blocks a user from holding all items
  noitem.nowear.*:
    description: Blocks a user from wearing all items
  noitem.nocook.*:
    description: Blocks a user from wearing all items
  noitem.noplace.*:
    description: Blocks a user from placing any item or block
  noitem.nobreak.*:
    description: Blocks a user from breaking any item or block
  noitem.nodrink.*:
    description: Blocks a user from drinking anything (broken currently)
  noitem.noopen.*:
    description: Blocks a user from opening anything
  noitem.nohave.*:
     description: Blocks a user from having anything
  noitem.noenchant.*:
     description: Blocks a user from enchanting anything
  noitem.no*:
    children:
      noitem.nocraft.*: true
      noitem.nopickup.*: true
      noitem.nodrop.*: true
      noitem.nobrew.*: true
      noitem.nouse.*: true
      noitem.nohold.*: true
      noitem.nowear.*: true
      noitem.nocook.*: true
      noitem.noplace.*: true
      noitem.nobreak.*: true
      noitem.nodrink.*: true
      noitem.noopen.*: true
      noitem.nohave.*: true
      noitem.noenchant.*: true
      

commands:
    noitem:
        description: NoItems only command, used to relode the config or claim items
        usage: /noitem [reload|claim]