name: NoItem
version: ${project.version}
website: http://dev.bukkit.org/server-mods/noitem/
description: Stops certain items from being crafted/picked up, effectivally removing them on the server.
authors: [nala3]

main: net.worldoftomorrow.nala.ni.NoItem
database: false
softdepend: [Vault]

permissions:
    noitem.admin:
        description: Allows access to noitem commands and admin notifications
    noitem.allitems:
        description: Negates all rescrictions on the player
    noitem.nohold.*:
        description: Blocks user from holding all items
    noitem.nocraft.*:
        description: Blocks user from crafting all items
    noitem.nodrop.*:
        description: Blocks user from dropping all items
    noitem.nopickup.*:
        description: Blocks user from picking up all items

commands:
    noitem:
        description: NoItems only command, used to relode the config or claim items
        usage: /noitem [reload|claim]